themes:
  - name: "SNR"
    colors:
      - "#00070D"
      - "#000F17"
      - "#001523"
      - "#001E2E"
      - "#012337"
      - "#062A41"
  - name: "SNS"
    colors:
      - "#000E1C"
      - "#041D32"
      - "#0B2F49"
      - "#07273E"
      - "#0F3953"
      - "#133F5C"

